p10k_home: /var/phenome-10k
p10k_logs: /var/log/phenome10k
p10k_src_dir: '{{ p10k_home }}/www'
p10k_admin_email: a.goswami@nhm.ac.uk
app_root_dir: '{{ p10k_src_dir }}/app'
static_files_dir: '{{ app_root_dir }}/static'
virtualenv_location: '{{ p10k_home }}/production'
venv_bin: '{{ virtualenv_location }}/bin'
gunicorn_binary: '{{ venv_bin }}/gunicorn'
mysql_root_password: plaEee2eer34@
p10k_db_user: phenome10k
p10k_db_password: Aei0)rr2rr2r2r2r
p10k_db_name: phenome10k
p10k_db_host: data
p10k_db_url: "mysql+pymysql://{{ p10k_db_user }}:{{ p10k_db_password|urlencode() }}@{{ p10k_db_host }}:3306/{{ p10k_db_name }}"
p10k_linux_user: phenome10k
p10k_linux_group: phenome10k
p10k_admin_password: pass
gunicorn_port: 8000
mmonit_admin_password: ilovemonit
mmonit_client_password: "{{ mmonit_admin_password }}"
hostname: phenome10k.localhost
monit_hostname: monit.phenome10k.localhost
virtual_ip: '192.168.10.21'
monit_mmonit_url: http://monit:{{ mmonit_client_password|urlencode() }}@{{ virtual_ip }}:8080/collector
nfs_path: '/var/files'
uploads_dir: '{{ nfs_path }}/uploads'
models_dir: '{{ nfs_path }}/models'
mmonit_license_owner: Vincent Smith
mmonit_license: "{{ lookup('hashi_vault', 'secret=phenome10k/mmonit:license url=https://man-vault-2.nhm.ac.uk:8200')}}"
vrrp_password: pass123
flask_secret_key: "G}<Ci&XWqSqA/mF7ZCWI7JJ.:QuuZF"

# To gain access to this inbox, look up the phenome10k/mailtrap:invite_url secret
postfix_relay_host: smtp.mailtrap.io
postfix_relay_port: 2525
postfix_sasl_auth_enable: 'yes'
postfix_sasl_mechanism_filter: plain
postfix_sasl_security_options: noanonymous
postfix_sasl_username: "{{ lookup('hashi_vault', 'secret=phenome10k/mailtrap:username url=https://man-vault-2.nhm.ac.uk:8200')}}"
postfix_sasl_password: "{{ lookup('hashi_vault', 'secret=phenome10k/mailtrap:password url=https://man-vault-2.nhm.ac.uk:8200')}}"
