p10k_home: /var/phenome-10k
p10k_logs: /var/log/phenome10k
p10k_src_dir: '{{ p10k_home }}/www'
app_root_dir: '{{ p10k_src_dir }}/app'
static_files_dir: '{{ app_root_dir }}/static'
virtualenv_location: '{{ p10k_home }}/production'
venv_bin: '{{ virtualenv_location }}/bin'
gunicorn_binary: '{{ venv_bin }}/gunicorn'
mysql_root_password: plaEee2eer34@
p10k_linux_user: phenome10k
p10k_linux_group: phenome10k
p10k_admin_password: pass
mmonit_admin_password: ilovemonit
mmonit_client_password: ilovemonit
hostname: phenome10k.localhost
monit_hostname: monit.phenome10k.localhost
virtual_ip: '192.168.10.21'
monit_mmonit_url: http://monit:{{ mmonit_client_password }}@{{ virtual_ip }}:8080/collector
nfs_path: '/var/files'
uploads_dir: '{{ nfs_path }}/uploads'
models_dir: '{{ nfs_path }}/models'
