---
# servers
server_ips:
  - '{{ data_server }}'
  - '{{ app_servers[0] }}'
  - '{{ app_servers[1] }}'
  - '{{ lb_servers[0] }}'
  - '{{ lb_servers[1] }}'

# folders
p10k_home: /var/phenome-10k
p10k_src_dir: '{{ p10k_home }}/www'
app_root_dir: '{{ p10k_src_dir }}/api'
frontend_root_dir: '{{ p10k_src_dir }}/web'
static_files_dir: '{{ p10k_src_dir }}/static'
thumbnail_dir: '{{ p10k_home }}/thumbnails'
virtualenv_location: '{{ p10k_home }}/production'
venv_bin: '{{ virtualenv_location }}/bin'
nfs_path: /var/files
models_dir: '{{ nfs_path }}/models'
tmp_upload_dir: '{{ nfs_path }}/tmp-uploads'
uploads_dir: '{{ nfs_path }}/uploads'
p10k_logs: /var/log/phenome10k
nginx_partial_configs_dir: /etc/nginx/parts
letsencrypt_dir: /etc/letsencrypt/live/www.phenome10k.org
certificates_dir: /etc/nginx/certificates

# firewall
trusted_networks:
  - 192.168.0.0/16
  - 127.0.0.0/16

# keepalived
virtual_ip: 192.168.10.21
vrrp_password: pass123

# monit
mmonit_admin_password: ilovemonit
mmonit_client_password: '{{ mmonit_admin_password }}'
mmonit_license: "{{ lookup('hashi_vault', 'secret=phenome10k/mmonit:license url=https://man-vault-2.nhm.ac.uk:8200')}}"
mmonit_license_owner: Vincent Smith
monit_mmonit_url: http://monit:{{ mmonit_client_password|urlencode() }}@{{ virtual_ip
  }}:8080/collector

# database
mysql_root_password: plaEee2eer34@
p10k_db_host: '{{ data_server }}'
p10k_db_name: phenome10k
p10k_db_password: Aei0_rr2rr2r2r2r
p10k_db_user: phenome10k
p10k_db_url: mysql+pymysql://{{ p10k_db_user }}:{{ p10k_db_password|urlencode() }}@{{
  p10k_db_host }}:3306/{{ p10k_db_name }}
mysql_monit:
  user_name: monit
  password: Monit_mysql_password.8

# nginx
max_upload_size_mb: 500
hostname: phenome10k.localhost
monit_hostname: 'monit.{{ hostname }}'
use_ssl: false

# nodejs
node_binary: /usr/bin/node
node_source: '{{ frontend_root_dir }}/node'
node_port: 8080
node_version: 14.x

# p10k: celery
celery_binary: '{{ venv_bin }}/celery'
rabbitmq_host: localhost
redis_host: localhost
celery_backend_url: redis://{{ redis_host }}:6379
celery_broker_url: amqp://{{ p10k_db_user }}:{{ p10k_db_password|urlencode() }}@{{
  rabbitmq_host }}:5672
flower_broker_api: http://{{ p10k_db_user }}:{{ p10k_db_password|urlencode() }}@{{
  rabbitmq_host }}:15672/api/

# p10k: flask
cache_redis_url: redis://{{ redis_host }}:6379/1
flask_secret_key: G}<Ci&XWqSqA/mF7ZCWI7JJ.:QuuZF
gunicorn_binary: '{{ venv_bin }}/gunicorn'
gunicorn_port: 8000
p10k_admin_email: a.goswami@nhm.ac.uk
p10k_admin_password: pass
password_salt: 7mrUh6kF*&PEh2gUTmHc
sysadmin_email: phenome10k@nhm.ac.uk

# p10k: hcaptcha
hcaptcha_secret_key: "{{ lookup('hashi_vault', 'secret=phenome10k/hcaptcha:secret_key url=https://man-vault-2.nhm.ac.uk:8200')}}"
hcaptcha_site_key: "{{ lookup('hashi_vault', 'secret=phenome10k/hcaptcha:site_key url=https://man-vault-2.nhm.ac.uk:8200')}}"

# p10k: mail
mail_host: smtp.mailtrap.io

# p10k: setup
skip_git_checkout: true

# users
p10k_linux_user: phenome10k
p10k_linux_group: phenome10k
