---
  - name: Create phenome10k group
    group:
      gid: 1234 # Give this number to Vagrant to rsync the source files as this group
      name: '{{ p10k_linux_group }}'
    become: y
  - name: Create phenome10k user
    user:
      name: '{{ p10k_linux_user }}'
      home: '{{ p10k_home }}'
    become: y
  - name: Set permissions on phenome10k home directory
    file:
      path: '{{ p10k_home }}'
      mode: '0750'
      owner: '{{ p10k_linux_user }}'
      group: '{{ p10k_linux_group }}'
      recurse: y
    become: y
  - name: Add nginx user to phenome10k group
    user:
      name: nginx
      groups: '{{ p10k_linux_group }}'
      append: yes
    become: y
