[tool.commitizen]
name = "cz_nhm"
version = "2.4.0"
tag_format = "v$version"
update_changelog_on_bump = true
changelog_incremental = true
version_files = [
    "api/pyproject.toml:version",
    "web/package.json:version"
]
