---

  - name: Install Postfix
    yum:
      name:
        - postfix
        - cyrus-sasl
        - cyrus-sasl-plain
      state: installed
    become: yes

  - name: Copy across postfix configuration
    template:
      src: main.cf.j2
      dest: "/etc/postfix/main.cf"
    become: yes
    notify:
      - reload postfix

  - name: Copy sender_canonical list
    template:
      src: sender_canonical.j2
      dest: /etc/postfix/sender_canonical
    become: yes
    notify:
      - rebuild sender_canonical
      - reload postfix

  - name: Copy across postfix sasl credentials
    template:
      src: sasl_passwd.j2
      dest: "/etc/postfix/sasl_passwd"
    notify:
      - reload postfix
    become: yes
    register: postfix_sasl_passwd
    when: postfix_sasl_username is defined

  - name: Rebuild password database
    shell: postmap /etc/postfix/sasl_passwd
    notify:
      - reload postfix
    become: yes
    when: postfix_sasl_passwd is changed

  - file:
      path: /etc/ssl/private
      state: directory
    become: y

  # - name: Copy ssl/ca files
  #   copy:
  #     src: '{{ item.key }}'
  #     dest: '{{ item.value }}/{{ item.key }}'
  #   with_dict:
  #     ca-certificates.crt: /etc/ssl/certs
  #     ssl-cert-snakeoil.key: /etc/ssl/private
  #     ssl-cert-snakeoil.pem: /etc/ssl/certs
  #   become: y
  #   notify:
  #     - reload postfix

  - file:
      state: touch
      path: /etc/postfix/virtual
    become: y
    register: touch_virtual

  - name: Rebuild virtual database
    shell: postmap /etc/postfix/virtual
    become: yes
    when: touch_virtual is changed
    notify:
      - reload postfix

  - file:
      state: touch
      path: /etc/postfix/virtual_domains
    become: y
    register: touch_virtual_domains

  - name: Rebuild virtual database
    shell: postmap /etc/postfix/virtual_domains
    become: yes
    when: touch_virtual_domains is changed
    notify:
      - reload postfix
