---
  - name: Install nfs utils
    yum:
      name: 'nfs-utils'
    become: yes

  - name: Create the directory mounts
    file:
      path: "{{ nfs_path }}"
      state: directory
    become: yes

  - name: Mount the folder from the file server
    mount:
      path: '{{ nfs_path }}'
      src: '{{ nfs_server }}:{{ nfs_path }}'
      fstype: nfs
      opts: 'rw,noacl,nocto,bg,ac,noatime,nodiratime,intr,hard'
      state: mounted
    become: yes
