mysql_root_password: "{{ lookup('hashi_vault', 'secret=phenome10k/mysql:root_password url=https://man-vault-2.nhm.ac.uk:8200')}}"
p10k_db_password: "{{ lookup('hashi_vault', 'secret=phenome10k/mysql:p10k_password url=https://man-vault-2.nhm.ac.uk:8200')}}"
p10k_db_name: phenome10k
p10k_db_host: ct-phen-1
nfs_server: ct-phen-1
app_servers:
  - app-p10k-1.nhm.ac.uk
  - app-p10k-2.nhm.ac.uk
p10k_db_url: "mysql+pymysql://{{ p10k_db_user }}:{{ p10k_db_password | urlencode | replace('/','%2F') }}@{{ p10k_db_host }}:3306/{{ p10k_db_name }}"
p10k_linux_user: phenome10k
p10k_linux_group: phenome10k
p10k_admin_password: "{{ lookup('hashi_vault', 'secret=phenome10k/p10k:admin_password url=https://man-vault-2.nhm.ac.uk:8200')}}"
mmonit_admin_password: "{{ lookup('hashi_vault', 'secret=phenome10k/mmonit:password url=https://man-vault-2.nhm.ac.uk:8200')}}"
hostname: phenome10k.org
monit_hostname: monit.phenome10k.org
virtual_ip: '157.140.2.106'
mmonit_license: "{{ lookup('hashi_vault', 'secret=phenome10k/mmonit:license url=https://man-vault-2.nhm.ac.uk:8200')}}"
postfix_relay_host: mailserver.nhm.ac.uk
postfix_sasl_auth_enable: false
vrrp_password: "{{ lookup('hashi_vault', 'secret=phenome10k/vrrp:password url=https://man-vault-2.nhm.ac.uk:8200')}}"
vrrp_interface: ens160
flask_secret_key: "{{ lookup('hashi_vault', 'secret=phenome10k/p10k:flask_secret url=https://man-vault-2.nhm.ac.uk:8200')}}"
trusted_networks:
  - '157.140.0.0/16'
  - '127.0.0.0/16'
skip_git_checkout: no
thumbnail_dir: '{{ p10k_src_dir }}/thumbnails'
mysql_monit:
  user_name: monit
  password: "{{ lookup('hashi_vault', 'secret=phenome10k/mysql:monit_password url=https://man-vault-2.nhm.ac.uk:8200')}}"