---
- name: Install nfs dependencies
  apt:
    name:
      - nfs-kernel-server
    state: present
  become: true

- name: Create the directory mount
  file:
    path: '{{ nfs_path }}'
    state: directory
    group: 1234
    mode: '0775'
  become: true

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart nfs
