"""Remove title from File model

Revision ID: 1cdbca4d6453
Revises: a85d1db64812
Create Date: 2019-04-26 14:52:11.060470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdbca4d6453'
down_revision = 'a85d1db64812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=250), nullable=False))

    # ### end Alembic commands ###
