"""uploads table

Revision ID: 600c38d10447
Revises: 6e10d09c97f2
Create Date: 2019-03-14 17:16:41.335933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600c38d10447'
down_revision = '6e10d09c97f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_timestamp'), 'upload', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_timestamp'), table_name='upload')
    op.drop_table('upload')
    # ### end Alembic commands ###
