"""Add size column to files

Revision ID: a85d1db64812
Revises: ee36c2cf4e0b
Create Date: 2019-04-16 16:42:42.333331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85d1db64812'
down_revision = 'ee36c2cf4e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer()))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('scan_attachment', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('scan_attachment', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.drop_column('size')

    # ### end Alembic commands ###
