"""add ctm relationship

Revision ID: f222f8856fa2
Revises: ef6bd83f563f
Create Date: 2019-03-26 13:01:06.262225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f222f8856fa2'
down_revision = 'ef6bd83f563f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.create_foreign_key('ctm_key', 'file', ['ctm_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_constraint('ctm_key', type_='foreignkey')

    # ### end Alembic commands ###
