---
  - name: Download node installer
    get_url:
      url: https://rpm.nodesource.com/setup_{{node_version}}
      dest: /tmp/setup_{{node_version}}.sh
      mode: 755
    become: y

  - name: Clear yum cache
    command: yum clean all
    args:
      creates: "{{ p10k_home }}/.node-{{node_version}}-installed"
    become: y

  - name: Install node rpm
    shell: /tmp/setup_{{node_version}}.sh
    args:
      creates: "{{ p10k_home }}/.node-{{node_version}}-installed"
    become: y

  - name: Mark node modules as needing rebuild
    command: "touch {{ p10k_home }}/.node-{{node_version}}-rebuild"
    args:
      creates: "{{ p10k_home }}/.node-{{node_version}}-installed"
    become: y

  - name: Mark node {{ node_version }} as installed
    copy:
      content: ""
      dest: "{{ p10k_home }}/.node-{{node_version}}-installed"
      force: no
      owner: phenome10k
    become: y

  - name: Install node
    yum:
      name:
        - nodejs
      state: latest
    become: y
    notify:
      - rebuild front end
      - restart node
