---
- name: Download nodejs setup script
  get_url:
    url: 'https://deb.nodesource.com/setup_{{ node_version }}'
    dest: /tmp/setup_node.sh
  become: true

- name: Make nodejs setup script executable
  file:
    dest: /tmp/setup_node.sh
    mode: a+x
  become: true

- name: Mark node modules as needing rebuild
  command: touch {{ p10k_home }}/.node-{{node_version}}-rebuild
  args:
    creates: '{{ p10k_home }}/.node-{{node_version}}-installed'
  become: true

- name: Mark node {{ node_version }} as installed
  copy:
    content: ''
    dest: '{{ p10k_home }}/.node-{{node_version}}-installed'
    force: false
    owner: phenome10k
  become: true

- name: Execute the node setup script
  shell: /tmp/setup_node.sh
  become: true

- name: Install node
  apt:
    name: nodejs
    state: present
  become: true
  notify:
    - rebuild front end
    - restart node

- name: Remove node setup script
  file:
    path: /tmp/setup_node.sh
    state: absent
  become: true
