---
- name: Install virtualenv
  apt:
    name:
      - python3-venv
    state: present
  become: true

- name: Create virtualenv
  command: python3 -m venv {{ virtualenv_location }}
  args:
    creates: '{{ virtualenv_location }}/bin'
  become: true
  become_user: phenome10k
