---
  - name: Install git, epel repository, etc
    yum:
      name:
        - git
        - epel-release
        - python-setuptools
        - libsemanage-python
        - policycoreutils-python
    become: y
  - name: Install python3
    yum:
      name:
        - python-pip
        - python36
        - python36-pip
        - python36-virtualenv
    become: yes
