---
- name: Install nginx
  apt:
    name: nginx
  become: true

- name: Copy nginx base config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  become: true

- name: Copy nginx non-ssl config
  template:
    src: phenome10k.org.conf.j2
    dest: /etc/nginx/conf.d/phenome10k.org.conf
  notify:
    - restart nginx
  become: true
  when: not use_ssl

- name: Copy nginx ssl config
  template:
    src: phenome10k.org.ssl.conf.j2
    dest: /etc/nginx/conf.d/phenome10k.org.conf
  notify:
    - restart nginx
  become: true
  when: use_ssl

- name: Start nginx
  systemd:
    name: nginx
    state: started
    enabled: true
  become: true
