---
- name: Install nginx
  apt:
    name: nginx
  become: true

- name: Copy nginx base config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  become: true

- name: Copy maintenance file
  copy:
    src: maintenance.html
    dest: /usr/share/nginx/html/maintenance.html.off
    owner: root
    group: root
  notify: restart nginx
  become: true

- name: Copy .well-known
  copy:
    src: .well-known
    dest: /var/www/
    mode: 0644
  notify: restart nginx
  become: true

- name: Check if certificates dir exists
  stat:
    path: '{{ letsencrypt_dir }}'
  register: certdir

- name: Copy nginx non-ssl config
  template:
    src: phenome10k.org.conf.j2
    dest: /etc/nginx/conf.d/phenome10k.org.conf
  notify:
    - restart nginx
  become: true
  when: (not use_ssl) or (not certdir.stat.islnk is defined)

- import_tasks: letsencrypt.yml
  tags:
    - letsencrypt
  when: use_ssl

- name: Copy nginx ssl config
  template:
    src: phenome10k.org.ssl.conf.j2
    dest: /etc/nginx/conf.d/phenome10k.org.conf
  notify:
    - restart nginx
  become: true
  when: use_ssl and certdir.stat.islnk is defined

- name: Start nginx
  systemd:
    name: nginx
    state: started
    enabled: true
  become: true
