---
- name: Install nginx
  apt:
    name: nginx
  become: true

- name: Copy nginx base config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  become: true

- name: Copy maintenance file
  copy:
    src: maintenance.html
    dest: /usr/share/nginx/html/maintenance.html.off
    owner: root
    group: root
  notify: restart nginx
  become: true

- name: Copy .well-known
  copy:
    src: .well-known
    dest: /var/www/
    mode: 0644
  notify: restart nginx
  become: true

- name: Copy robots.txt
  copy:
    src: robots.txt
    dest: /var/www/
    mode: 0644
  notify: restart nginx
  become: true

- name: Create partial configs directory
  file:
    path: '{{ nginx_partial_configs_dir }}'
    state: directory
  become: true

- name: Copy server body config
  template:
    src: server-body.conf.j2
    dest: '{{ nginx_partial_configs_dir }}/server-body.conf'
  notify:
    - restart nginx
  become: true

- name: Copy blocked useragents config
  copy:
    src: blocked-useragents.conf
    dest: '{{ nginx_partial_configs_dir }}/blocked-useragents.conf'
  notify:
    - restart nginx
  become: true

- import_tasks: self-signed.yml
  when: use_ssl

- name: Check if letsencrypt certificates dir exists
  stat:
    path: '{{ letsencrypt_dir }}'
  register: lecertdir
  become: true

# always use self-signed certificates for the backup lb because we can't autorenew
# letsencrypt without disabling the main lb

- name: Copy self-signed certificates config
  template:
    src: self-signed.conf.j2
    dest: '{{ nginx_partial_configs_dir }}/ssl_certs.conf'
  notify:
    - restart nginx
  become: true
  when: use_ssl and ((not lecertdir.stat.islnk is defined) or vrrp_state == 'BACKUP')

- name: Copy letsencrypt certificates config
  template:
    src: letsencrypt.conf.j2
    dest: '{{ nginx_partial_configs_dir }}/ssl_certs.conf'
  notify:
    - restart nginx
  become: true
  when: use_ssl and lecertdir.stat.islnk is defined and vrrp_state == 'MASTER'

- name: Copy nginx non-ssl config
  template:
    src: phenome10k.org.conf.j2
    dest: /etc/nginx/conf.d/phenome10k.org.conf
  notify:
    - restart nginx
  become: true
  when: not use_ssl

- name: Copy nginx ssl config
  template:
    src: phenome10k.org.ssl.conf.j2
    dest: /etc/nginx/conf.d/phenome10k.org.conf
  notify:
    - restart nginx
  become: true
  when: use_ssl

- import_tasks: letsencrypt.yml
  tags:
    - letsencrypt
  when: use_ssl and vrrp_state == 'MASTER'

- name: Start nginx
  systemd:
    name: nginx
    state: started
    enabled: true
  become: true
