---
  - name: rebuild node modules
    command: npm rebuild
    args:
      chdir: '{{ p10k_src_dir }}'
    environment:
      NODE_ENV: production
    become: y
    become_user: phenome10k

  - name: rebuild front end
    command: node {{ p10k_src_dir }}/build
    args:
      chdir: '{{ p10k_src_dir }}'
    environment:
      NODE_ENV: production
    become: y
    become_user: phenome10k

  - name: restart gunicorn
    service:
      name: gunicorn
      state: restarted
    become: y

  - name: restart node
    service:
      name: node
      state: restarted
    become: y

  - name: restart task queue
    service:
      name: task-queue
      state: restarted
    become: y
