---
- name: Create mmonit dir
  file:
    path: '{{ mmonit_dir }}'
    state: directory
  become: true

- name: Download mmonit
  get_url:
    url: https://www.mmonit.com/dist/mmonit-{{ mmonit_version }}-linux-x64.tar.gz
    dest: '{{ mmonit_dir }}/mmonit-{{ mmonit_version }}-linux-x64.tar.gz'
      # Checksum seems to be constantly changing??
      # checksum: sha256:{{ mmonit_checksum }}
  become: true
  register: download_monit

- name: Extract mmonit source
  unarchive:
    extra_opts:
      - --strip-components=1
    src: '{{ mmonit_dir }}/mmonit-{{ mmonit_version }}-linux-x64.tar.gz'
    remote_src: true
    dest: '{{ mmonit_dir }}'
    owner: root
    group: root
    mode: '0644'
  become: true
  when: download_monit.changed

- name: Install sqlite3
  apt:
    name: sqlite3
    state: present
  become: true

  # Update default passwords - can only be done in the database before it starts

- name: Update M/Monit admin user
  command: >
    sqlite3 {{ mmonit_dir }}/db/mmonit.db "
    SELECT count(*) FROM users WHERE uname='admin' AND password != '{{ password }}';
    UPDATE users SET password='{{ password }}' WHERE uname='admin';"
  vars:
    password: "{{ mmonit_admin_password | hash('md5') | upper }}"
  become: true
  register: update_admin
  changed_when: update_admin.stdout == '1'

- name: Update M/Monit client user
  command: >
    sqlite3 {{ mmonit_dir }}/db/mmonit.db "
    SELECT count(*) FROM users WHERE uname='admin' AND password != '{{ password }}';
    UPDATE users SET password='{{ password }}' WHERE uname='monit';"
  vars:
    password: "{{ mmonit_client_password | hash('md5') | upper }}"
  become: true
  register: update_client
  changed_when: update_client.stdout == '1'

- name: Copy server xml template
  template:
    src: server.xml.j2
    dest: '{{ mmonit_dir }}/conf/server.xml'
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Copy service script template
  template:
    src: mmonit.service.j2
    dest: /etc/systemd/system/mmonit.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - restart mmonit

- name: Make script executable
  file:
    path: '{{ mmonit_dir }}/bin/mmonit'
    mode: '0755'
  become: true

- name: Enable mmonit service
  systemd:
    name: mmonit
    enabled: true
  become: true

- meta: flush_handlers
