---
  - hosts: app
    roles:
      - python
      - users
      - firewalld
      - openctm
      - nodejs
      - phenome-10k
      - monit/monit
    vars:
      monit_services:
        - gunicorn
        - systems
        - 50gb-root-partition

    # Cron gbif
    # Email
    # Backups
# https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvii-deployment-on-linux
# https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xv-a-better-application-structure

  - hosts: lb
    roles:
      - python
      - firewalld
      - nginx
      - monit/monit
      - monit/mmonit
      - keepalived
    vars:
      monit_services:
        - nginx
        - systems
        - 50gb-root-partition
