---
  - hosts: all
    roles:
      - python
      - users
      - firewalld
      - openctm
      - nodejs
      - mysql
      - phenome-10k
      - nginx
    vars:
      p10k_home: /var/phenome-10k
      p10k_src_dir: '{{ p10k_home }}/www'
      app_root_dir: '{{ p10k_src_dir }}/app'
      static_files_dir: '{{ app_root_dir }}/static'
      virtualenv_location: '{{ p10k_home }}/production'
      venv_bin: '{{ virtualenv_location }}/bin'
      gunicorn_binary: '{{ venv_bin }}/gunicorn'
      root_password: plaEee2eer34@
      p10k_linux_user: phenome10k
      p10k_linux_group: phenome10k
      p10k_db_user: phenome10k
      p10k_db_password: Platypodes3!
      p10k_db_name: phenome10k

    # Monitoring
    # Cron gbif
    # Email
# https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvii-deployment-on-linux
# https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xv-a-better-application-structure
