---
  - hosts: app
    roles:
      - python
      - users
      - firewalld
      - openctm
      - nodejs
      - mysql
      - phenome-10k
      - monit/monit
      - monit/mmonit

    # Cron gbif
    # Email
    # Backups
# https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvii-deployment-on-linux
# https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xv-a-better-application-structure

  - hosts: lb1
    roles:
      - firewalld
      - nginx


# Todo:
  # Remove mysql to docker service
  #
