---
  - hosts: data
    roles:
      - python
      - firewalld
      - nfs/server
      - mysql
  - hosts: app
    roles:
      - python
      - users
      - firewalld
      - openctm
      - nfs/client
      - nodejs
      - phenome-10k
      - monit/monit
    vars:
      monit_services:
        - gunicorn
        - systems
        - 50gb-root-partition

    # Cron gbif
    # Email
    # Backups

  - hosts: lb
    roles:
      - python
      - firewalld
      - nginx
      - monit/monit
      - monit/mmonit
      - keepalived
    vars:
      monit_services:
        - nginx
        - systems
        - 50gb-root-partition
