---
- name: Install keepalived
  apt:
    name: keepalived
    state: present
  become: true

- name: Create template
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  become: true
  notify:
    - restart keepalived

- name: Create Health script
  template:
    src: health.sh
    dest: /etc/keepalived/health.sh
    mode: preserve
  become: true

- name: Start keepalived
  service:
    name: keepalived
    state: started
    enabled: true
  become: true
