---
- name: Copy RabbitMQ setup script
  copy:
    src: rabbitmq-setup-20240322.sh
    dest: /tmp/rabbitmq-setup.sh
    mode: a+x
  become: true

- name: Run RabbitMQ setup script
  shell: /tmp/rabbitmq-setup.sh
  become: true

- name: Remove RabbitMQ setup script
  file:
    path: /tmp/rabbitmq-setup.sh
    state: absent
  become: true

- name: Copy RabbitMQ advanced config file
  template:
    src: rabbitmq-advanced.config
    dest: /etc/rabbitmq/advanced.config
  become: true
  notify:
    - restart rabbitmq

- name: Copy RabbitMQ config file
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
  become: true
  notify:
    - restart rabbitmq

- meta: flush_handlers

- name: Start/enable RabbitMQ
  systemd:
    name: rabbitmq-server.service
    state: started
    enabled: true
  become: true

- name: Enable RabbitMQ management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  become: true

- name: Add RabbitMQ user
  rabbitmq_user:
    user: '{{ p10k_db_user }}'
    password: '{{ p10k_db_password }}'
    node: rabbit@localhost
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  become: true

- name: Delete RabbitMQ guest user
  rabbitmq_user:
    user: guest
    state: absent
    node: rabbit@localhost
  become: true

- name: Install Redis
  apt:
    name:
      - redis
    state: present
  become: true
  notify:
    - restart redis

- name: Start/enable Redis
  systemd:
    name: redis.service
    state: started
    enabled: true
  become: true

- name: Create the celery service
  template:
    src: celery.service.j2
    dest: /etc/systemd/system/celery.service
  become: true
  notify:
    - restart celery

- name: Enable celery service
  systemd:
    name: celery.service
    state: started
    enabled: true
  become: true

- name: Create the flower service
  template:
    src: flower.service.j2
    dest: /etc/systemd/system/flower.service
  become: true
  notify:
    - restart flower

- name: Enable flower service
  systemd:
    name: flower.service
    state: started
    enabled: true
  become: true
