---
- name: Install git
  apt:
    name:
      - git
    state: present
  become: true

- name: Check out source
  git:
    repo: https://github.com/NaturalHistoryMuseum/phenome-10k.git
    dest: '{{ p10k_src_dir }}'
    version: main
    force: y
  become: true
  become_user: phenome10k
  when: not skip_git_checkout
  notify:
    - rebuild front end
    - restart gunicorn
    - restart node
  tags:
    - flask
    - node
    - celery

- name: Ensure phenome10k group owns the src folder
  file:
    path: '{{ p10k_src_dir }}'
    group: phenome10k
    mode: '0770'
    recurse: true
  become: true

- name: And the backend folder
  file:
    path: '{{ app_root_dir }}'
    group: phenome10k
    mode: '0770'
    recurse: true
  become: true

- name: And the frontend folder
  file:
    path: '{{ frontend_root_dir }}'
    group: phenome10k
    mode: '0770'
    recurse: true
  become: true

- name: Copy env variables
  template:
    src: .env.j2
    dest: '{{ p10k_home }}/.env'
  become: true
  become_user: phenome10k
  notify:
    - restart gunicorn

- name: Create log directory
  file:
    path: '{{ p10k_logs }}'
    state: directory
    owner: phenome10k
  become: true

- name: Create upload directories
  file:
    path: '{{ item }}'
    state: directory
    owner: phenome10k
    group: phenome10k
  loop:
    - '{{ uploads_dir }}'
    - '{{ models_dir }}'
    - '{{ tmp_upload_dir }}'
  become: true

- import_tasks: app-flask.yml
  tags:
    - flask

- import_tasks: app-node.yml
  tags:
    - node

- import_tasks: app-celery.yml
  tags:
    - celery

- name: Add the gbif cron job
  cron:
    name: GBIF update
    minute: '0'
    hour: '0'
    day: '1'
    month: '*'
    job: '{{ venv_bin }}/p10k update-gbif-tags'
  become: true
  become_user: phenome10k

- name: Add cron job to clear tmp_uploads directory
  cron:
    name: Clear tmp_uploads
    minute: '0'
    hour: '0'
    day: '*'
    month: '*'
    job: find {{ tmp_upload_dir }} -type f -mtime +1 -delete
  become: true
  become_user: phenome10k

- name: Configure logrotate
  copy:
    src: p10k-logrotate.conf
    dest: /etc/logrotate.d/phenome10k
    owner: root
    group: root
  become: true
