---
  - name: Check out source
    git:
      repo: "https://github.com/NaturalHistoryMuseum/phenome-10k.git"
      dest: '{{ p10k_src_dir }}'
      version: main
      force: y
    become: y
    become_user: phenome10k
    when: not skip_git_checkout
    notify:
      - rebuild front end
      - restart gunicorn
      - restart node

  - name: Ensure phenome10k group owns the src folder
    file:
      path: '{{ p10k_src_dir }}'
      group: phenome10k
      mode: '0770'
    become: y

  - name: And the backend folder
    file:
      path: '{{ app_root_dir }}'
      group: phenome10k
      mode: '0770'
    become: y

  - name: And the frontend folder
    file:
      path: '{{ frontend_root_dir }}'
      group: phenome10k
      mode: '0770'
    become: y

  - name: Allow nginx to read from static files dir
    sefcontext:
      target: '{{ static_files_dir }}(/.*)?'
      setype: httpd_sys_content_t
    become: y

  - name: Apply new SELinux file context to filesystem
    command: 'restorecon -Rv {{ static_files_dir }}'
    become: y
    register: restorecon
    changed_when: 'restorecon.stdout !=  ""'

  - name: Copy env variables
    template:
      src: .env.j2
      dest: '{{ p10k_home }}/.env'
    become: y
    become_user: phenome10k
    notify:
      - restart gunicorn

  - name: Create log directory
    file:
      path: '{{ p10k_logs }}'
      state: directory
      owner: phenome10k
    become: y

  - name: Create upload directories
    file:
      path: '{{ item }}'
      state: directory
      owner: phenome10k
      group: phenome10k
    loop:
      - "{{ uploads_dir }}"
      - "{{ models_dir }}"
      - "{{ tmp_upload_dir }}"
    become: y

  - import_tasks: app-flask.yml
    tags:
      - flask
  - import_tasks: app-node.yml
    tags:
      - node
  - import_tasks: app-celery.yml
    tags:
      - celery

  - name: Add the gbif cron job
    cron:
      name: GBIF update
      minute: "0"
      hour: "0"
      day: "1"
      month: "*"
      job: "{{ venv_bin }}/p10k update-gbif-tags"
    become: y
    become_user: phenome10k

  - name: Add cron job to clear tmp_uploads directory
    cron:
      name: Clear tmp_uploads
      minute: "0"
      hour: "0"
      day: "*"
      month: "*"
      job: "find {{ tmp_upload_dir }} -type f -mtime +1 -delete"
    become: y
    become_user: phenome10k
