"""
Add queue.

Revision ID: 4420116fa319
Revises: e64692114f90
Create Date: 2021-05-11 16:44:22.287485
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4420116fa319'
down_revision = 'e64692114f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'queue',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('method', sa.String(length=255), nullable=True),
        sa.Column('arguments', sa.JSON(), nullable=True),
        sa.Column(
            'created',
            sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue')
    # ### end Alembic commands ###
