"""Add storage_area to File

Revision ID: e64692114f90
Revises: 214e8c781632
Create Date: 2019-05-21 15:13:55.862626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64692114f90'
down_revision = '214e8c781632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_area', sa.Enum('uploads', 'models'), server_default='uploads', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('storage_area')

    # ### end Alembic commands ###
