---
  - name: Install firewalld
    yum:
      name: firewalld
      state: present
    become: y

  - name: Start Firewalld
    service:
      name: "firewalld"
      state: started
      enabled: yes
    become: y

  - name: Enable the dmz zone for internal connections
    firewalld:
      zone: dmz
      state: present
      permanent: true
    become: y

  - name: Add trusted network IPs to DMZ group
    firewalld:
      zone: dmz
      state: enabled
      source: '{{ item }}'
      permanent: true
      immediate: true
    loop: '{{ trusted_networks }}'
    become: y
